name: Deploy to DigitalOcean

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.DIGITALOCEAN_SSH_HOST}} # IP address of the server you wish to ssh into
        key: ${{secrets.DIGITALOCEAN_SSH_PRIVATE_KEY}} # Private or public key of the server
        username: ${{ secrets.DIGITALOCEAN_SSH_USERNAME }} # User of the server you want to ssh into
        script: |
          git clone https://github.com/kauesv/SMARTify.git
          git pull main
