name: Deploy to DigitalOcean

on:
  workflow_run:
    workflows: ["test"] # Nome do workflow de CI que é executado antes do deploy
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.DIGITALOCEAN_SSH_HOST}} # IP address of the server you wish to ssh into
        key: ${{secrets.DIGITALOCEAN_SSH_PRIVATE_KEY}} # Private or public key of the server
        username: ${{ secrets.DIGITALOCEAN_SSH_USERNAME }} # User of the server you want to ssh into
        script: |
          cd SMARTify
          git pull origin main
          echo 'Deployment successful to digital ocean'
          sudo docker-compose up -d --build
