name: Deploy to Heroku

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Heroku CLI
        uses: akshnz/heroku-cli-action@v1.2
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

      - name: Log in to Heroku Container Registry
        run: heroku container:login

      - name: Build and push Docker image
        run: |
          heroku container:push web -a ${{ secrets.HEROKU_APP_NAME }}

      - name: Release Docker image
        run: |
          heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
