name: Deploy to DigitalOcean

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
        ssh-passphrase: ${{ secrets.DIGITALOCEAN_SENHA }}

    - name: Add known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    - name: Deploy via SSH with password
      run: |
        ssh -o StrictHostKeyChecking=no root@159.89.225.51"
          git pull origin main &&
          sudo docker-compose up -d --build
