name: Deploy to Heroku

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Heroku Using Docker Container
        uses: cloutojp/heroku-deploy@v2.0.7
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          # Your Heroku API Key
          api_key: ${{ secrets.HEROKU_API_KEY }}
          # Your Heroku App Name
          app_name: smartify-v01
          # Dokerfile path
          dockerfile_path: Dockerfile
                
                
