name: Deploy to DigitalOcean

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}

    - name: Deploy via SSH with password
      run: |
        ssh -o StrictHostKeyChecking=no root@167.172.129.82"
          git pull origin main &&
          sudo docker-compose up -d --build
