name: Deploy to DigitalOcean

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: DigitalOcean App Platform deployment
      # You may pin to the exact commit or the version.
      # uses: digitalocean/app_action@94ed240e4d0ff6cff2020be713f2eb10d9404ad0
      uses: digitalocean/app_action@v1.1.6
      with:
        app_name: smartify-v01
        # DigitalOcean Personal Access Token.(use https://docs.digitalocean.com/reference/api/create-personal-access-token/ for creating new token)
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}
          
