name: Test APP

on:
  push:
    branches: [ 'develop' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.12.2', '3.11']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and Create DB
        run: |
          docker-compose up -d --build

      - name: Run tests
        run: pytest