name: Test APP

on:
  push:
    branches: [ 'develop' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          python -m pip install --upgrade pip

      - name: Build and Create DB
        run: |
          docker-compose up -d --build

      - name: Aguarde até que o MongoDB esteja pronto
        run: |
          echo "Waiting for MongoDB to be ready..."
          until docker exec mongodb mongosh --eval "print('MongoDB is up')" &>/dev/null; do
          sleep 1
          done

      - name: Run tests
        run: docker exec app pytest